### ISSUE TITLE
Error TS2742 when generating declaration types with trpc.router

### ISSUE THREAD

**Issue by jgoux** [trpc/trpc#1945]
Hello all,

I'm trying to set up a demo monorepo full ESM + TypeScript and I want to use trpc for the API part. 👌 
I currently have an issue when generating declaration types for the project:

```
src/router.ts:6:14 - error TS2742: The inferred type of 'appRouter' cannot be named without a reference to '../../../node_modules/@trpc/server/dist/internals/procedure.js'. This is likely not portable. A type annotation is necessary.
```

Related code is here: https://github.com/jgoux/acme/blob/main/apps/api/src/router.ts#L6

To reproduce run these commands:
```bash
yarn
yarn workspace @acme/api build
```

Note that I'm using `@trpc/server@10.0.0-alpha.22`, the stable version wasn't correctly importable with ESM, discussion about it here: https://discord.com/channels/867764511159091230/894984069291581511/979830057994432522

What's funny is that the `tsc --noEmit` is fine and doesn't report the error. 😂 

I'm not sure what to do about this particular TS error, this is a new one to me. 🤔

**Comment by jgoux** [comment]
As pointed out in Typescript's issue here: https://github.com/microsoft/TypeScript/issues/42873#issuecomment-1140506416 I've found a "fix". 

It's still unclear if the error originates from how TypeScript resolves types or if something is technically wrong in the usage of TypeScript in trpc.

**Comment by KATT** [comment]
Will close this for now, feel free to reopen once there's a _more_ stable version :)

**Comment by jgoux** [comment]
> Will close this for now, feel free to reopen once there's a _more_ stable version :)

Hey Alex, in fact, it was fixed by https://github.com/trpc/trpc/pull/1960 👍 

Have a great weekend!

**Comment by DivMode** [comment]
Hi, I am getting close to the same issue when using turborepo with pnpm:

Type error: The inferred type of 'trpc' cannot be named without a reference to '.pnpm/react-query@3.39.2_biqbaboplfbrettd7655fr4n2y/node_modules/react-query'. This is likely not portable. A type annotation is necessary.

**Comment by jgoux** [comment]
@DivMode Could you try the `node-linker=hoisted` option for pnpm? I had issues using pnpm default linker strategy.

https://github.com/jgoux/acme/blob/2fb707a7d4bdd2068b6eb5159c42910f92226e22/.npmrc#L1

**Comment by DivMode** [comment]
@jgoux Added that file to root where pnpm-workspace is in but still get the same error.
