### ISSUE TITLE
feat: re-implement server-side websocket.

### ISSUE THREAD

**Issue by romanzy313** [trpc/trpc#6598]
### Describe the feature you'd like to request

I am the creator of the `trpc-uwebsockets` adapter, and I would like to implement a WebSocket core for the tRPC server. I have found issue #6109, where help was wanted for the client side. I believe that enhancements on the server side can also greatly benefit this awesome project! Here are my reasons for making this proposal:

Firstly, each adapter must implement WebSocket functionality separately, currently 305 LOC for `ws` and 674 LOC for `trpc-uwebsockets`. I had to reimplement mostly everything from scratch, including copy-pasting types. v11 `ws` adapter is built around the `ws` library API.

Secondly, the current implementation does weird hacks for context promise resolution. There are many edge cases leading to race conditions, which are challenging to test robustly.

Thirdly, the `ws` adapter creates a lot of closures and has hanging promises, which I assume are not GC-friendly. Performance could be improved, but this will need a proper benchmarking setup.

### Describe the solution you'd like to see

I propose that two-way communication is modeled with javascript standard `ReadableStream` and `WriteableStream`. This way, the adapters for all servers, such as `ws`, `uWebSockets.js`, `Bun`, `Cloudflare Workers`, etc., can share the same "duplex communication glue." Furthermore, existing core request handlers fit nicely into this implementation, as v11 embraces `Request` and `Response` primitives. I think it's about time to modernize the WebSockets server core. Ideally, this should ship before v11 :)

What are your thoughts on this? I can start implementing it for `ws` and `trpc-uwebsockets`. My plan is to design the API with `ws` in mind, as it is more widely used. I would like to become a maintainer once this is included in the stable core. Additionally, funding for this implementation would be much appreciated.

### Describe alternate solutions

Current `ws` implementation can be abstracted, but that would create more misdirection.

### 👨‍👧‍👦 Contributing

- [x] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by romanzy313** [comment]
I got a little bit carried away and mostly implemented the server-side code. Forget `ReadableStream` and `WriteableStream`, that was me thinking out loud. Integration with other servers should be straightforward now. Still, there is a lot of work to do to make it prod ready. You can check the code in my branch for [core](https://github.com/romanzy313/trpc/blob/issues/6598/packages/server/src/adapters/ws.ts) and [ws adapter](https://github.com/romanzy313/trpc/blob/issues/6598/packages/server/src/unstable-core-do-not-import/ws/ws.ts).

I want to discuss changing the WebSocket protocol a bit in order to simplify how `connectionParams` are handled. The old implementation is too complex. I suggest that for WebSockets, `connetionParams` is always the first message, even if the user doesn't define them. Then, the server should ack after the context is resolved. The client must not send any messages until the `link_ready` response is received. Example of such a message:

```jsonc
{
  id: null; // or 0? 
  jsonrpc?: '2.0'; 
  result: {
    type: 'link_ready'; // always 'link_ready' for context initialized
  },
}
```

This change removes most race conditions and greatly simplifies the code. Async IIFE with danging promises are gone, and types can be reused. This is the complete implementation of a `ws` adapter:

```ts
/* eslint-disable no-restricted-imports */

import type ws from 'ws';
import type { AnyRouter } from '../unstable-core-do-not-import';
import {
  newWsHandler,
  type WsClient,
  type WSHandlerOptions,
} from '../unstable-core-do-not-import/ws/ws';
import { incomingMessageToRequestWithoutBody } from './node-http';

export type WSSHandlerOptions<TRouter extends AnyRouter> =
  WSHandlerOptions<TRouter> & {
    wss: ws.WebSocketServer;
  };

export function applyWSSHandler<TRouter extends AnyRouter>(
  opts: WSSHandlerOptions<TRouter>,
) {
  const handler = newWsHandler(opts);

  opts.wss.on('connection', (client, req) => {
    if (opts.prefix && !req.url?.startsWith(opts.prefix)) {
      return;
    }

    const fetchReq = incomingMessageToRequestWithoutBody(req);
    const wsClient = client satisfies WsClient;

    const connection = handler.newConnection(fetchReq, wsClient);

    // eslint-disable-next-line @typescript-eslint/no-base-to-string
    client.on('message', (data) => connection.onMessage(data.toString()));
    client.on('error', (cause) => connection.onError(cause));
    client.on('close', (code) => connection.onClose(code));
  });
  return {
    broadcastReconnectNotification: () =>
      handler.broadcastReconnectNotification(),
  };
}

```

Currently, the tests for the ws adapter do not pass because of the protocol change. I get lots of errors like "TRPCError: Malformed TRPCConnectionParamsMessage". The protocol change (and change to  `wsLink`) must be done first to keep the core simple. Also, other official adapters like Fastify fail too.

**Comment by romanzy313** [comment]
I have implemented an inefficient compatibility version that avoids the protocol change in [this branch](https://github.com/romanzy313/trpc/tree/issues/6598-compat). This is the approach used to avoid resolving a promise from the outer scope 😅 

```ts
let iter = 0;
while (contextState != CONTEXT_STATE_RESOLVED && iter < 100) {
  await new Promise((resolve) => setTimeout(resolve, 10));
  iter++;
}
if (iter == 100) {
  throw Error('failed to resolve context in time');
}
```

All tests are passing except for one, but the current behavior is more correct, and the test needs to be altered.

And this is how Fastify plugin looks like

```ts
fastify.get(prefix ?? '/', { websocket: true }, async (socket, req) => {
  const incomingMessage: IncomingMessage = req.raw;
  const fetchReq = incomingMessageToRequestWithoutBody(incomingMessage);

  const wsClient = socket satisfies WsClient;
  const connection = handler.newConnection(fetchReq, wsClient);

  // eslint-disable-next-line @typescript-eslint/no-base-to-string
  socket.on('message', (data) => connection.onMessage(data.toString()));
  socket.on('error', (cause) => connection.onError(cause));
  socket.on('close', (code) => connection.onClose(code));
});
```

**Comment by KATT** [comment]
@hmatthieu maybe you could work together with @romanzy313 on this one? 👀

**Comment by hmatthieu** [comment]
Hey @romanzy313,

Just to give you a bit more info about the current wsAdapter — the recent refactoring was mainly aimed at splitting the code to improve readability, so there's definitely room for the logic to be improved.

I'm quite a fan of using uWebSockets on the server. I did some tests on my side and saw great performance. Also, I've been interested in implementing pub/sub for tRPC — see [this discussion](https://github.com/trpc/trpc/discussions/6160).

I'll check out your branches and try to give some feedback on your suggestions :)

**Comment by romanzy313** [comment]
I have created a pull request with clean changes for your review, compatible with existing protocol for the connection params. The issue with how server-side websockets are currently implemented, is that they require `ws` server as an argument, and they throw errors to be caught by outer scope when the context fails. This change provides a clean abstraction layer.

Still, the context is resolved in a messy way, because how connection params are defined in the protocol is not good in my opinion... Unfortunately, v11 just dropped, so I don't think this large breaking change is possible (maybe v12?)

@hmatthieu I did not see the discussion, I guess because I was not directly mentioned? Im glad to say that the adapter now supports v11. Ill discuss pub/sub there as to not clutter this issue.

**Comment by hmatthieu** [comment]
Hey @romanzy313, sorry for the long absence. I tried to review your code, but I feel like I don't have enough experience to give meaningful feedback. Nothing really jumped out at me, except maybe one console.log that could probably be removed (maybe something you forgot). For now, I’ll stick to focusing on the WS client only.
